paths = [
    "./",
    "./wasmy-macros/",
    "./wasmy-abi/",
    "./wasmy-vm/",
]

[cargo-new]
vcs = "none"
[alias]
wasm = "build --target=wasm32-wasi --example"
svm = "run --example=svm -- --path_prefix=../../wasm32-wasi/debug/examples"
dvm = "run --example=dvm -- --path_prefix=../../wasm32-wasi/debug/examples"
